server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: passenger-service
          uri: lb://passenger-service
          predicates:
            - Path=/passengers/**
        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/search/**
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/bookings/**
        - id: checkin-service
          uri: lb://checkin-service
          predicates:
            - Path=/checkins/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notifications/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payments/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
