server:
  port: 8081
spring:

  application:
    name: search-service
  datasource:
    url: jdbc:h2:mem:searchdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"  # Active tous les endpoints Actuator
